import re
import json
import uuid
import io
import zipfile


# ---------- HELPERS ----------
def parse_json_block(text: str) -> dict:
    text = text.strip()
    text = re.sub(r"^```(?:json)?|```$", "", text, flags=re.MULTILINE).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start == -1 or end == -1:
            raise ValueError("AI did not return JSON")
        return json.loads(text[start:end + 1])


def make_zip(files: dict[str, str]) -> bytes:
    """Build a zip in memory from {path: content}."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for path, content in files.items():
            z.writestr(path, content)
    buf.seek(0)
    return buf.getvalue()


# ---------- WEBSITE ----------
WEBSITE_SYSTEM = """You are a senior front-end engineer.
Return ONLY a valid JSON object with this exact shape:
{
  "title": "string",
  "html": "full HTML including <head> and <body>",
  "css": "CSS",
  "js": "JavaScript"
}
No markdown. No explanation. Just JSON.
"""


async def generate_website(prompt: str) -> tuple[bytes, str]:
    from ai_client import ask_ai

    raw = await ask_ai(WEBSITE_SYSTEM, prompt)
    data = parse_json_block(raw)

    html = data.get("html", "<html><body></body></html>")
    css = data.get("css", "")
    js = data.get("js", "")
    title = data.get("title", "Generated Site")

    if "</head>" in html and css:
        html = html.replace("</head>", f"<style>{css}</style></head>")
    if "</body>" in html and js:
        html = html.replace("</body>", f"<script>{js}</script></body>")

    files = {
        "index.html": html,
        "style.css": css,
        "script.js": js,
        "README.md": f"# {title}\n\nGenerated by ForgeAI.\n",
    }

    return make_zip(files), title


# ---------- APK ----------
APK_SYSTEM = """You are a senior Android developer using Kotlin + Jetpack Compose + Gradle (Kotlin DSL).

Return ONLY a JSON object:
{
  "app_name": "string",
  "package": "com.example.appname",
  "files": [
    {"path": "app/src/main/java/.../MainActivity.kt", "content": "..."},
    {"path": "app/build.gradle.kts", "content": "..."},
    {"path": "build.gradle.kts", "content": "..."},
    {"path": "settings.gradle.kts", "content": "..."},
    {"path": "gradle.properties", "content": "..."},
    {"path": "app/src/main/AndroidManifest.xml", "content": "..."}
  ]
}
No markdown. No explanation. Just JSON.
"""


async def generate_android_project(prompt: str) -> tuple[bytes, str]:
    from ai_client import ask_ai

    raw = await ask_ai(APK_SYSTEM, prompt, max_tokens=8000)
    data = parse_json_block(raw)

    files = {}
    for f in data.get("files", []):
        files[f["path"]] = f["content"]

    # Ensure minimum required files exist
    files.setdefault(
        "settings.gradle.kts",
        f'rootProject.name = "{data.get("app_name", "App")}"\ninclude(":app")\n',
    )
    files.setdefault(
        "gradle.properties",
        "android.useAndroidX=true\norg.gradle.jvmargs=-Xmx2048m\n",
    )
    files.setdefault(
        ".github/workflows/build.yml",
        """name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - run: chmod +x gradlew
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
""",
    )

    zip_bytes = make_zip(files)
    return zip_bytes, data.get("app_name", "App")
